import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import '@/styles/globals.css'
import { yekanBakh, yekanBakhEn } from "@/app/ui/fonts";// import "swiper/css";
// import '@/styles/globals.css';
import "swiper/css";
import "swiper/css/autoplay";
import "swiper/css/effect-fade";
import "swiper/css/navigation";
import '../styles/globals.css'
import CommonProvider from "@/lib/hooks/common";
// import 'react-tabs/style/react-tabs.css';
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl"  className={`${yekanBakh.variable} ${yekanBakhEn.variable} `}>
      <body>
      <CommonProvider>
          {children}
      </CommonProvider>
      </body>
    </html>
  )
}
