export type Icons =
    | "globe"
    | "Loc"
    | "search"
    | "search1"
    | "phone"
    | "mail"
    | "arrowPrev2"
    | "instagram"
    | "user"
    | "whatsapp"
    | "youtube"
    | "linkedin"
    | "ArrowRight"
    | "ArrowLeft"
    | "arrowPrev"
    | "plus"
    | "hamburger-menu"
    | "user-bold"
    | "arrow-left"
    | "message-two"
    | "error"
    | "eye"
    | "eye-slash"
    | "cancel"
    | "play"
    | "facebook"
;
